// Mocks generated by Mockito 5.4.2 from annotations
// in weather_app/test/doubles/repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/data/remote_datasources/informacoes_do_tempo_remote_datasource.dart'
    as _i2;
import 'package:weather_app/domain/entities/informacoes_do_tempo.dart' as _i3;
import 'package:weather_app/domain/repositories/informacoes_do_tempo_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInformacoesDoTempoRemoteDatasource_0 extends _i1.SmartFake
    implements _i2.InformacoesDoTempoRemoteDatasource {
  _FakeInformacoesDoTempoRemoteDatasource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInformacoesDoTempo_1 extends _i1.SmartFake
    implements _i3.InformacoesDoTempo {
  _FakeInformacoesDoTempo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InformacoesDoTempoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInformacoesDoTempoRepository extends _i1.Mock
    implements _i4.InformacoesDoTempoRepository {
  MockInformacoesDoTempoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InformacoesDoTempoRemoteDatasource
      get informacoesDoTempoRemoteDatasource => (super.noSuchMethod(
            Invocation.getter(#informacoesDoTempoRemoteDatasource),
            returnValue: _FakeInformacoesDoTempoRemoteDatasource_0(
              this,
              Invocation.getter(#informacoesDoTempoRemoteDatasource),
            ),
          ) as _i2.InformacoesDoTempoRemoteDatasource);

  @override
  _i5.Future<_i3.InformacoesDoTempo> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue:
            _i5.Future<_i3.InformacoesDoTempo>.value(_FakeInformacoesDoTempo_1(
          this,
          Invocation.method(
            #get,
            [],
          ),
        )),
      ) as _i5.Future<_i3.InformacoesDoTempo>);
}
